name: "Auto-pre-release for experimental branch"

on:
  push:
    branches:
      - "experimental"

jobs:
  pre-release:
    name: "experimental-pre-release"
    runs-on: "ubuntu-latest"

    steps:
    - name: "Pull from latest experimental branch"
      uses: "actions/checkout@v3"
    - name: "Set up JDK 17"
      uses: "actions/setup-java@v3"
      with:
        java-version: "17"
        distribution: "temurin"
        cache: "maven"
    - name: "Build with Maven"
      run: mvn -B package --file pom.xml

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ github.ref }}"
        prerelease: true
        title: "Experimental pre-release"
        files: |
          LICENSE
          **.jar
