name: "Auto-release for main branch"

on:
  push:
    tags:
       - "release"
jobs:
  pre-release:
    name: "main-release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Pull from latest main branch"
        uses: "actions/checkout@v3"
      - name: "Set up JDK 19"
        uses: "actions/setup-java@v3"
        with:
          java-version: "19"
          distribution: "oracle"
          cache: "maven"
      - name: "Build with Maven"
        run: mvn -B package --file pom.xml

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Main release"
          files: |
            LICENSE
            **.jar
